spring:
  application:
    name: football
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: packt
    password: packt
    hikari:
      maximum-pool-size: 4
  jpa:
# no longer needed: database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Best to always use open-in-view: false
    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
management:
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,env,metrics,beans,loggers,prometheus
  tracing:
    sampling:
      probability: 0.01